# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_loss_prj <- function(nS, dS, mS, PS, xS, muS) {
    .Call('_mosub_fast_loss_prj', PACKAGE = 'mosub', nS, dS, mS, PS, xS, muS)
}

rcpparma_hello_world <- function() {
    .Call('_mosub_rcpparma_hello_world', PACKAGE = 'mosub')
}

rcpparma_outerproduct <- function(x) {
    .Call('_mosub_rcpparma_outerproduct', PACKAGE = 'mosub', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_mosub_rcpparma_innerproduct', PACKAGE = 'mosub', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_mosub_rcpparma_bothproducts', PACKAGE = 'mosub', x)
}

